#!/usr/bin/env python3
"""Copy the versioned new-project skill to agent discovery directories."""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "skills/new-project"
DESTINATIONS = (
    ROOT / ".agents/skills/new-project",
    ROOT / ".claude/skills/new-project",
)
OLD_CODEX_COPY = ROOT / ".codex/skills/new-project"
MARKER = ".generated-from-skills-new-project"


def files(directory: Path) -> dict[str, bytes]:
    return {
        path.relative_to(directory).as_posix(): path.read_bytes()
        for path in directory.rglob("*")
        if path.is_file() and path.name != MARKER
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify generated copies")
    args = parser.parse_args()

    if SOURCE.is_symlink() or not (SOURCE / "SKILL.md").is_file():
        raise SystemExit("skills/new-project must be a real versioned directory")
    if any(path.is_symlink() for path in SOURCE.rglob("*")):
        raise SystemExit("skills/new-project contains a symbolic link")

    expected = files(SOURCE)
    if OLD_CODEX_COPY.is_symlink():
        raise SystemExit(f"Refusing to remove a symbolic link: {OLD_CODEX_COPY}")
    if OLD_CODEX_COPY.exists():
        if not OLD_CODEX_COPY.is_dir() or not (OLD_CODEX_COPY / MARKER).is_file():
            raise SystemExit(f"Refusing to remove a non-generated directory: {OLD_CODEX_COPY}")
        if args.check:
            raise SystemExit(f"Obsolete generated skill copy remains: {OLD_CODEX_COPY}")
        shutil.rmtree(OLD_CODEX_COPY)

    for destination in DESTINATIONS:
        if args.check:
            if (
                destination.is_symlink()
                or not destination.is_dir()
                or not (destination / MARKER).is_file()
                or any(path.is_symlink() for path in destination.rglob("*"))
                or files(destination) != expected
            ):
                raise SystemExit(f"Generated skill copy is missing or stale: {destination}")
            continue
        if destination.is_symlink():
            destination.unlink()
        elif destination.exists():
            if not (destination / MARKER).is_file():
                raise SystemExit(f"Refusing to replace a non-generated directory: {destination}")
            shutil.rmtree(destination)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(SOURCE, destination)
        (destination / MARKER).write_text("Generated by machine/sync-house-skills.py\n")
    print("new-project copies OK" if args.check else "new-project copies updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
